chart_type: candle
time_frame: 1M
update_interval: 30
enable_pre_post: true
show_volumes: true

symbols:
    - ACM
    - ADBE
    - ADSK
    - AMT
    - AVTR
    - BAH
    - BMI
    - BSX
    - CMG
    - CPNG
    - CPRT
    - CRTO
    - CTAS
    - DOCS
    - DPZ
    - DUOL
    - EXLS
    - HLNE
    - HRL
    - INTU
    - IPAR
    - ISRG
    - JKHY
    - LDOS
    - LULU
    - MA
    - MCD
    - MORN
    - MSFT
    - NKE
    - NOC
    - NOMD
    - ODD
    - PAYX
    - PCTY
    - PLNT
    - PODD
    - QLYS
    - RACE
    - RMD
    - ROL
    - SMPL
    - TTEK
    - TYL
    - UHS
    - ULTA
    - VEEV
    - VITL
