chart_type: candle
time_frame: 1M
update_interval: 30
enable_pre_post: true
show_volumes: true

symbols:
    - ACM
    - ADBE
    - ADSK
    - AMT
    - AVTR
    - AWI
    - BAH
    - BMI
    - BSX
    - CMG
    - CPNG
    - CPRT
    - DOCS
    - DPZ
    - DUOL
    - EXLS
    - HLNE
    - INTU
    - IPAR
    - ISRG
    - JKHY
    - LDOS
    - LULU
    - MCD
    - MORN
    - MSFT
    - NFLX
    - NKE
    - NOMD
    - ODD
    - OLED
    - PAYX
    - PCTY
    - PEP
    - PLNT
    - QLYS
    - RACE
    - ROL
    - TYL
    - ULTA
    - VEEV
    - VITL
